### ISSUE TITLE
MutableProperty/Propertyの使用

### ISSUE THREAD

**Issue by dazy1030** [torakyun/yumemi_training#34]
## 概要
* `MutableProperty/Property` を使用してAPIの状態が更新した時の処理を行なってください
* Actionには `isExecuting: Property<Bool>` という変数があり、これはActionが実行中かどうかの変数です
* isExecutingを使ってアクティビティインジケータのアニメーションの切り替えを行なってください

## `MutableProperty/Property` とは
* 普通の変数のように、いつでも値を知ることができ（Signalはできない）、SignalやSignalProducerのように変更を監視することができる
```swift
let mutableProperty = MutableProperty<Int>(1)
// .value で値にアクセスする
print(mutableProperty.value)
// Signalのように変更を監視できる
mutableProperty.signal.observeValues { value in
    print(value)
}
mutableProperty.value = 2
// 2
```
* MutablePropertyは値を変更することができるが、Propertyは変更できない
    * `let` で定義しても .value から変更できるため
    * 逆にいうと、全てletで定義することを推奨

**Comment by torakyun** [comment]
https://github.com/torakyun/yumemi_training/pull/35
こちらで対応しました。
